main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "main"

urlpatterns = [
    path(route="", view=views.home, name="home"),
    path(route="about", view=views.about, name="about"),
    path(route="contact", view=views.contact, name="contact"),
    path(route="categories", view=views.categories, name="categories"),
    path(route="profile/my_posts", view=views.my_posts, name="my_posts"),
    path(route="profile/my_posts/<int:id>", view=views.individual_post, name="individual_post"),
    path(route="categories/<str:categ>", view=views.category, name="category"),
    path(route="categories/category_processor/<str:categ>", view=views.category_processor, name="category_processor"),
    path(route="posts/<str:q>", view=views.posts_query, name="posts_query")
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recomiendamelo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("login/", view=auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", view=auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path("signup/", view=views.signup, name="signup"),
    path("profile/", view=views.profile, name="profile"),
    path("profile_update/", view=views.profile_update, name="profile_update")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db.models import Model, CharField, IntegerField, ForeignKey, DateTimeField, ManyToManyField, ForeignKey, SET_NULL, CASCADE
from django.contrib.auth.models import User

# Create your models here.

class Post(Model):

    CATEGORY_CHOICES = [
        ("producto","Producto"),
        ("empresa","Empresa"),
        ("música","Música"),
        ("pelicula","Pelicula"),
        ("famoso","Famoso"),
        ("vida","Vida"),
    ]

    user = ForeignKey(to=User, on_delete=SET_NULL, null=True)
    title = CharField(verbose_name="title", max_length=300, help_text="What is your post about?", unique=True)
    category = CharField(verbose_name="category", max_length=8, choices=CATEGORY_CHOICES, default="vida", help_text="what category is it?")
    date_created = DateTimeField(verbose_name="date", auto_now_add=True, help_text="when this post was created")

    def __str__(self) -> str:
        return self.title



class Tag(Model):

    name = CharField(verbose_name="name", max_length=20, help_text="the name of the tag")
    posts = ManyToManyField(to=Post)

    def __str__(self) -> str:
        return self.name


class Comment(Model):
    post = ForeignKey(to=Post, on_delete=CASCADE)
    user = ForeignKey(to=User, on_delete=SET_NULL, null=True)
    text = CharField(verbose_name="text", max_length=300)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.post.title}"

users/models.py
from django.db.models import Model, OneToOneField, CASCADE, IntegerField, TextField, ImageField
from django.contrib.auth.models import User

# Create your models here.


class Profile(Model):

    GENDER_CHOICES = [
        ('Male','male'),
        ('Female','female'),
        ('Other','other')
    ]

    user = OneToOneField(to=User, on_delete=CASCADE)
    age = IntegerField(verbose_name="age", blank=True, null=True)
    gender = TextField(verbose_name='gender', blank=True, null=True, choices=GENDER_CHOICES)
    profile_pic = ImageField(verbose_name='profile picture', default='profile_pic.jpg', upload_to='profile_pics')

    def __str__(self) -> str:
        return f'{self.user.username} - Profile'

users/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.forms import EmailField, CharField, ModelForm, IntegerField, ImageField


class UserUpdateForm(ModelForm):
    username = CharField(max_length=20, required=False, label="username", help_text="Max 20 letters long")

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(ModelForm):
    age = IntegerField(required=False)
    gender = CharField(required=False)
    profile_pic = ImageField(required=False)
    
    class Meta:
        model = Profile
        fields = ['age', 'gender', 'profile_pic']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .decorators import not_logged_user
from .forms import UserUpdateForm, ProfileUpdateForm
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.

@not_logged_user
def signup(response):
    if response.method == "POST":
        form = UserCreationForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("/login")
        else:
            return redirect("/signup")
    elif response.method == "GET":
        form = UserCreationForm()
        return render(response, "users/signup.html", {"form":form})


@login_required
def profile(request):
    context = {}
    if request.method == "POST":
        user = User.objects.get(id=request.user.id)
        context.update({"user":user})
        if request.POST.get("new_post") == "clicked":
            new_title, new_category = request.POST.get("title"), request.POST.get("category")
            new_post = Post.objects.create(user=user, title=new_title, category=new_category)
            new_post.save()
            context.update({"new_post":new_post})
    else:
        context.update({"user":request.user})
    return render(request, "users/profile.html", context=context)


@login_required
def profile_update(request):
    if request.method == "POST":
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_update_form.is_valid() and profile_update_form.is_valid():
            user_update_form.save()
            profile_update_form.save()
    else:
        user_update_form = UserUpdateForm()
        profile_update_form = ProfileUpdateForm()
    context = {'u_form': user_update_form, 'p_form': profile_update_form}
    return render(request, 'users/profile_update.html', context=context)

users/templates/users/login.html
{% extends "main/index.html" %}
{% load static %}


{% block title %}Login{% endblock title %}
{% block upper_area %}
{% block header %}
<!-- header section strats -->
<div style="background-color: blue;">
    <header class="header_section">
    <div class="container-fluid">
        <nav  class="navbar navbar-expand-lg custom_nav-container">
        <a class="navbar-brand" href="{% url 'main:home' %}">
            <img src="{% static 'main/images/logo.png' %}" alt="Logo" />
            <span>
            Spering
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:about' %}"> About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Work </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:categories' %}"> Category </a>
            </li>
            {% if user.is_autheticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}"> My Profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:my_posts' %}"> My Posts </a>
            </li>
            {% endif %}
            </ul>
            <div class="user_option">
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}">
                <span>
                  Logout
                </span>
              </a>
              {% else %}
              <a href="{% url 'signup' %}">
                <span>
                  Sign Up
                </span>
                <span> / </span>
              </a>
              <a href="{% url 'login' %}">
                  <span>
                  Login
                  </span>
              </a>
              {% endif %}
            <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
            </form>
            </div>
        </div>
        <div>
            <div class="custom_menu-btn ">
            <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
            </button>
            </div>
        </div>

        </nav>
    </div>
    </header>
</div>
<!-- end header section -->
{% endblock header %}
{% endblock upper_area %}
{% block slider %}{% endblock slider %}
{% block login %}
<!-- experience section -->

<section class="experience_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="img-box">
          <img src="{% static 'main/images/experience-img.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-7">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              Porque Nacimos Para Quejarnos
            </h2>
          </div>
          <p>
            Acá tenemos el poder de expresar lo que sentimos y nuestras opiniones sobre lo que nos gusta y lo que no. Ingresa al mundo de la opinios y dejanos saber que piensas.
          </p>
          <form method="post" action="#">
            {{form}}
            {% csrf_token %}
            <div class="btn-box">
                <button type="submit" class="btn-2" name="btn_login">Log In</button>
            </div>
          </form>
          <p></p>
          <p>I don't have an account. Sign up <a href="{% url 'signup' %}">here</a>.</p>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- end experience section -->
{% endblock login %}
{% block category %}{% endblock category %}
<!--{% block about %}{% endblock about %}-->
{% block new_posts %}{% endblock new_posts %}

users/templates/users/logout.html
{% extends 'main/index.html' %}
{% load 'static' %}

{% block title %}Logout{% endblock title %}

users/templates/users/profile.html
{% extends "main/index.html" %}
{% load static %}

{% block slider %}
<!-- slider section -->
<section class="slider_section ">
  <div class="carousel_btn-container">
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">01</li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1">02</li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2">03</li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-5 offset-md-1">
              <div class="detail-box">
                <h1>
                  {{user.username}}
                </h1>
                <p>
                  {{user.first_name}} {{user.last_name}}
                  {{user.email}}
                </p>
                <div class="btn-box">
                  <a href="{% url 'profile_update' %}" class="btn-2">
                    Edit Profile
                  </a>
                </div>
              </div>
            </div>
            <div class="offset-md-1 col-md-4 img-container">
              <div class="img-box">
                <img src="{{user.profile.profile_pic.url}}" alt="{{user.username}}">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item ">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-5 offset-md-1">
              <div class="detail-box">
                <h1>
                  You Can <br>
                  Hire Freelancer <br>
                  Here
                </h1>
                <p>
                  It is a long established fact that a reader will be distracted by
                  the readable content of a page
                </p>
                <div class="btn-box">
                  <a href="" class="btn-1">
                    About Us
                  </a>
                  <a href="" class="btn-2">
                    Get A Quote
                  </a>
                </div>
              </div>
            </div>
            <div class="offset-md-1 col-md-4 img-container">
              <div class="img-box">
                <img src="{% static 'main/images/slider-img.png' %}" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item ">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-5 offset-md-1">
              <div class="detail-box">
                <h1>
                  You Can <br>
                  Hire Freelancer <br>
                  Here
                </h1>
                <p>
                  It is a long established fact that a reader will be distracted by
                  the readable content of a page
                </p>
                <div class="btn-box">
                  <a href="" class="btn-1">
                    About Us
                  </a>
                  <a href="" class="btn-2">
                    Get A Quote
                  </a>
                </div>
              </div>
            </div>
            <div class="offset-md-1 col-md-4 img-container">
              <div class="img-box">
                <img src="{% static 'main/images/slider-img.png' %}" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</section>
<!-- end slider section -->
{% endblock slider %}


{% block login %}
<!-- experience section -->

<section class="experience_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="img-box">
          <img src="{% static 'main/images/experience-img.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-7">
        <div class="detail-box">
            <form action="#", method="post">
                <h3>Create A Post</h3>
                {% csrf_token %}
                <div class="heading_container">
                    <label for="title">
                      <span>Title</span>
                      <input type="text" id="title" placeholder="Write your question..." name="title" required maxlength="200">
                    </label>
                    <label for="cursos">
                      <span>Category</span>
                      <select name="category" id="category" required>
                        <option value="vida" selected>Vida</option>
                        <option value="producto">Producto</option>
                        <option value="empresa">Empresa</option>
                        <option value="música">Música</option>
                        <option value="pelicula">Pelicula</option>
                        <option value="famoso">Famoso</option>
                      </select>
                    </label>
                    <label for="tag">
                      <span>Tag</span>
                      <input type="text" id="tag" name="tag" placeholder="Escribe un tag (opcional)">
                    </label>
                </div>
                <div class="btn-box">
                    <button type="submit" class="btn-2" name="new_post" value="clicked">
                    Create
                    </button>
                </div>
            </form>
            <p>
              {% if new_post %}
               {{new_post.title}}
              {% endif %}
              {% if post_info %}
               {{post_info}}
              {% endif %}
            </p>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- end experience section -->
{% endblock login %}


{% block category %}{% endblock category %}

<!--{% block about %}{% endblock about %}-->


{% block new_posts %}
<!-- client popular posts -->
<section class="client_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-10 mx-auto">
        <div class="heading_container">
          <h2>
            <a href="{% url 'main:my_posts'  %}">My Posts</a>
          </h2>
        </div>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="detail-box">
                <h4>
                  {{user.post_set.first.category}}
                </h4>
                <p>
                  {{user.post_set.first.title}}
                </p>
                <img src="{% static 'main/images/quote.png' %}" alt="">
              </div>
            </div>
            {% for post in user.post_set.all %}
              {% if post != user.post_set.first %}
                <div class="carousel-item">
                  <div class="detail-box">
                    <h4>
                      {{post.category}}
                    </h4>
                    <p>
                      {{post.title}}
                    </p>
                    <img src="{% static 'main/images/quote.png' %}" alt="">
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- end client section -->
{% endblock new_posts %}

users/templates/users/profile_update.html
{% extends 'main/index.html' %}
{% load static %}

{% block title %}Update Profile{% endblock title %}

{% block upper_area %}
{% block header %}
<!-- header section strats -->
<div style="background-color: blue;">
    <header class="header_section">
    <div class="container-fluid">
        <nav  class="navbar navbar-expand-lg custom_nav-container">
        <a class="navbar-brand" href="{% url 'main:home' %}">
            <img src="{% static 'main/images/logo.png' %}" alt="Logo" />
            <span>
            Spering
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="about.html"> About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="work.html">Work </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="category.html"> Category </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}"> My Profile</a>
            </li>
            </ul>
            <div class="user_option">
              {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">
                    <span>
                    Logout
                    </span>
                </a>
              {% else %}
              <a href="{% url 'signup' %}">
                <span>
                  Sign Up
                </span>
                <span> / </span>
              </a>
              <a href="{% url 'login' %}">
                  <span>
                  Login
                  </span>
              </a>
              {% endif %}
            <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
            </form>
            </div>
        </div>
        <div>
            <div class="custom_menu-btn ">
            <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
            </button>
            </div>
        </div>

        </nav>
    </div>
    </header>
</div>
<!-- end header section -->
{% endblock header %}
{% endblock upper_area %}
{% block slider %}{% endblock slider %}

{% block login %}
<!-- experience section -->

<section class="experience_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="img-box">
          <img src="{% static 'main/images/experience-img.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-7">
        <div class="detail-box">
            <form action="#", enctype="multipart/form-data", method="post">
                {% csrf_token %}
                <div class="heading_container">
                    {{u_form}}
                </div>
                <p>
                    {{p_form}}
                </p>
                <div class="btn-box">
                    <a href="{% url 'profile' %}" class="btn-1">
                    Cancel
                    </a>
                    <button type="submit" class="btn-2">
                    Update
                    </button>
                </div>
            </form>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- end experience section -->
{% endblock login %}

users/templates/users/signup.html
{% extends "main/index.html" %}
{% load static %}

{% block title %}Sign Up{% endblock title %}
{% block upper_area %}
{% block header %}
<!-- header section strats -->
<div style="background-color: blue;">
    <header class="header_section">
    <div class="container-fluid">
        <nav  class="navbar navbar-expand-lg custom_nav-container">
        <a class="navbar-brand" href="{% url 'main:home' %}">
            <img src="{% static 'main/images/logo.png' %}" alt="Logo" />
            <span>
            Spering
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="about.html"> About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="work.html">Work </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="category.html"> Category </a>
            </li>
            </ul>
            <div class="user_option">
              <a href="{% url 'signup' %}">
                <span>
                  Sign Up
                </span>
                <span> / </span>
              </a>
            <a href="{% url 'login' %}">
                <span>
                Login
                </span>
            </a>
            <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
            </form>
            </div>
        </div>
        <div>
            <div class="custom_menu-btn ">
            <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
            </button>
            </div>
        </div>

        </nav>
    </div>
    </header>
</div>
<!-- end header section -->
{% endblock header %}
{% endblock upper_area %}
{% block slider %}{% endblock slider %}
{% block login %}
<!-- experience section -->

<section class="experience_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="img-box">
          <img src="{% static 'main/images/experience-img.jpg' %}" alt="Man ready to complain">
        </div>
      </div>
      <div class="col-md-7">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              Porque Nacimos Para Quejarnos
            </h2>
          </div>
          <p>
            <b>Crea tu cuenta con nosotros para quejarte cuanto quieras.</b>
          </p>
          <form method="post" action="#">
            {{form}}
            {% csrf_token %}
            <div class="btn-box">
                <button type="submit" class="btn-2" name="btn_login">Sign Up</button>
            </div>
            <p>I already have an account.</p>
            <div class="btn-box">
                <a href="{% url 'login' %}" class="btn-1">
                Log In
                </a>
            </div>
          </form>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- end experience section -->
{% endblock login %}
{% block category %}{% endblock category %}
<!--{% block about %}{% endblock about %}-->
{% block new_posts %}{% endblock new_posts %}