main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "main"

urlpatterns = [
    path(route="", view=views.home, name="home"),
    path(route="about", view=views.about, name="about"),
    path(route="contact", view=views.contact, name="contact"),
    path(route="categories", view=views.categories, name="categories"),
    path(route="profile/my_posts", view=views.my_posts, name="my_posts"),
    path(route="profile/my_posts/<int:id>", view=views.individual_post, name="individual_post"),
    path(route="categories/<str:categ>", view=views.category, name="category"),
    path(route="categories/category_processor/<str:categ>", view=views.category_processor, name="category_processor"),
    path(route="posts/<str:q>", view=views.posts_query, name="posts_query")
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recomiendamelo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("login/", view=auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", view=auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path("signup/", view=views.signup, name="signup"),
    path("profile/", view=views.profile, name="profile"),
    path("profile_update/", view=views.profile_update, name="profile_update")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db.models import Model, CharField, IntegerField, ForeignKey, DateTimeField, ManyToManyField, ForeignKey, SET_NULL, CASCADE
from django.contrib.auth.models import User

# Create your models here.

class Post(Model):

    CATEGORY_CHOICES = [
        ("producto","Producto"),
        ("empresa","Empresa"),
        ("música","Música"),
        ("pelicula","Pelicula"),
        ("famoso","Famoso"),
        ("vida","Vida"),
    ]

    user = ForeignKey(to=User, on_delete=SET_NULL, null=True)
    title = CharField(verbose_name="title", max_length=300, help_text="What is your post about?", unique=True)
    category = CharField(verbose_name="category", max_length=8, choices=CATEGORY_CHOICES, default="vida", help_text="what category is it?")
    date_created = DateTimeField(verbose_name="date", auto_now_add=True, help_text="when this post was created")

    def __str__(self) -> str:
        return self.title



class Tag(Model):

    name = CharField(verbose_name="name", max_length=20, help_text="the name of the tag")
    posts = ManyToManyField(to=Post)

    def __str__(self) -> str:
        return self.name


class Comment(Model):
    post = ForeignKey(to=Post, on_delete=CASCADE)
    user = ForeignKey(to=User, on_delete=SET_NULL, null=True)
    text = CharField(verbose_name="text", max_length=300)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.post.title}"

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def home(response):
    posts = Post.objects.all()[:20]
    context = {"posts":posts}
    return render(response, "main/index.html", context)


def about(request):
    return render(request, "main/about.html", {})


def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        subject = request.POST.get("subject")
        email = request.POST.get("email")
        message = request.POST.get("message")

        send_mail(
            subject=subject,
            message=f"{name}/n{message}",
            from_email=email,
            recipient_list=[User.objects.get(username="strovosky1").email] #Who will receive the email (You)
        )
    return render(request, "main/contact.html", {})


def categories(request):
    if request.method == "POST":
        if request.POST.get("search_btn") == "clicked":
            q = request.POST.get("post_search")
            return HttpResponseRedirect(reverse("main:posts_query", args=(q,)))
            
    return render(request, "main/categories.html", {})

@login_required
def my_posts(request):
    my_posts = Post.objects.filter(user_id=request.user.id).reverse()
    context = {"my_posts":my_posts}

    pagination =    Paginator(my_posts, 3)
    page = request.GET.get("page")
    paginated_posts = pagination.get_page(page)

    context.update({"paginated_posts":paginated_posts})    

    return render(request, "main/my_posts.html", context)


def individual_post(request, id):
    post = Post.objects.get(id=id)
    if request.method == "POST":
        if request.POST.get("delete_post_btn") == f"{post.id}":
            post.delete()
            return HttpResponseRedirect(reverse('main:my_posts'))
        elif request.POST.get("create_comment") == f"{post.id}":
            new_comment = Comment.objects.create(post=post, user=User.objects.get(id=request.user.id), text=request.POST.get("comment_text"))
            new_comment.save()
        context = {"post":post}
        return render(request, "main/individual_post.html", context)
    context = {"post":post}
    return render(request, "main/individual_post.html", context)


def category(request, categ):
    posts = Post.objects.filter(category=categ).reverse()
    context = {"posts":posts}

    pagination = Paginator(posts, 3)
    page = request.GET.get("page")
    paginated_posts = pagination.get_page(page)

    context.update({"paginated_posts":paginated_posts, "category":categ})

    return render(request, "main/category.html", context)


def category_processor(request, categ):
    return HttpResponseRedirect(reverse("main:category", args=(categ,)))


def posts_query(request, q):
    posts = Post.objects.filter(title__icontains=q)

    pagination = Paginator(posts, 5)
    page = request.GET.get("page")
    paginated_posts = pagination.get_page(page)

    context = {"paginated_posts":paginated_posts}

    return render(request, "main/posts.html", context)
    

main/templates/main/about.html
{% extends "main/index.html" %}

{% load static %}

{% block title %}About Us{% endblock title %}

{% block slider %}<!-- about section -->

<section class="about_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-9 mx-auto">
        <div class="img-box">
          <img src="images/about-img.jpg" alt="">
        </div>
      </div>
    </div>
    <div class="detail-box">
      <h2>
        About Spering Company
      </h2>
      <p>
        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If youThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you
      </p>
      <a href="">
        Read More
      </a>
    </div>
  </div>
</section>

<!-- end about section -->

{% endblock slider %}

{% block login %}{% endblock login %}

{% block about %}{% endblock about %}

{% block new_posts %}{% endblock new_posts %}






main/templates/main/categories.html
{% extends "users/login.html" %}
{% load static %}

{% block login %}{% endblock %}


{% block category %}
<!-- category section -->

  <section class="category_section layout_padding">
    <form action="" method="post">
        {% csrf_token %}
        <input type="search" placeholder="Search" name="post_search">
        <button type="submit" name="search_btn" value="clicked">Search</button>
    </form>
  <div class="container">
      <a href="{% url 'main:categories' %}">
          <div class="heading_container">
              <h2>
                  Category
              </h2>
          </div>
      </a>
      <div class="category_container">
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c1.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'producto' %}" >Productos</a>
          </h5>
          </div>
      </div>
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c2.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'empresa' %}" >Empresas</a>
          </h5>
          </div>
      </div>
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c3.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'musica' %}" >Música</a>
          </h5>
          </div>
      </div>
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c4.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'pelicula' %}" >Peliculas</a>
          </h5>
          </div>
      </div>
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c5.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'famoso' %}" >Famosos</a>
          </h5>
          </div>
      </div>
      <div class="box">
          <div class="img-box">
          <img src="{% static 'main/images/c6.png' %}" alt="">
          </div>
          <div class="detail-box">
          <h5>
              <a href="{% url 'main:category_processor' 'vida' %}" >Vida</a>
          </h5>
          </div>
      </div>
      </div>
  </div>
  </section>
<!-- end category section -->
{% endblock category %}


main/templates/main/category.html
{% extends "main/my_posts.html" %}
{% load static %}



{% block new_posts %}
<section class="client_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 col-md-10 mx-auto">
          <div class="heading_container">
            <h2>
              {{category}}
            </h2>
          </div>
          {% for post in paginated_posts %}
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="detail-box">
                  <h4>
                    {{post.user.username}}
                  </h4>
                  <a href="{% url 'main:individual_post' post.id %}" >
                    {{post.title}}
                  </a>
                  <p>
                    {{post.category}}
                  </p>
                  <img src="{% static 'main/images/quote.png' %}" alt="">
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
{% endblock new_posts %}  

main/templates/main/contact.html
{% extends "main/index.html" %}

{% load static %}


{% block login %}
<!-- experience section -->

<section class="experience_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="img-box">
          <img src="{% static 'main/images/experience-img.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-7">
        <div class="detail-box">
            <form action="#" method="post">
                {% csrf_token %}
                <div class="heading_container">
                    <h2>
                    Reaching out to us is very easy:
                    </h2>
                </div>
                <label for="name">
                    <span>Name</span>
                    <input type="text" id="name" name="name" maxlength="40" placeholder="Your name..." required>
                </label>
                <label for="email">
                    <span>Email</span>
                    <input type="text" name="email" id="email" maxlength="100" placeholder="Your email..." required>
                </label>
                <label for="subject">
                    <input type="text" name="subject" id="subject" maxlength="150" placeholder="What's the message about" required>
                </label>
                <label for="message">
                    <span>Message</span>
                    <input type="text" name="message" id="message" maxlength="500" placeholder="Your message..." required>
                </label>
                <div class="btn-box" >
                    <button class="btn-2" name="submit_email_btn" value="clicked" >Submit</button>
                </div>
            </form>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- end experience section -->
{% endblock login %}

main/templates/main/individual_post.html
{% extends "main/my_posts.html" %}
{% load static %}

{% block new_posts %}
<section class="client_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 col-md-10 mx-auto">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="detail-box">
                    <div class="heading_container">
                        <h2>
                            {{post.title}}
                        </h2>
                    </div>
                  <h4>
                    {{post.user.username}}
                  </h4>
                  <p>
                    {{post.category}}
                  </p>
                  <img src="{% static 'main/images/quote.png' %}" alt="Quotation mark">
                  {% if user.id == post.user.id %}
                  <p></p>
                  <form method="post">
                    {% csrf_token %}
                    <button type="submit" name="delete_post_btn" value="{{post.id}}">Delete Post</button>
                  </form>
                  {% endif %}
                  {% if user.is_authenticated %}
                  <p></p>
                  <form method="post">
                    {% csrf_token %}
                    <input type="text" name="comment_text" placeholder="Write your comment...">
                    <button type="submit" name="create_comment" value="{{post.id}}">Comment</button>
                  </form>
                  {% endif %}
                  <p></p>
                  {% for comment in post.comment_set.all %}
                    <ul>
                      <li>{{comment.text}}</li>
                    </ul>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock new_posts %}

main/templates/main/my_posts.html
{% extends "users/login.html" %}
{% load static %}

{% block login %}{% endblock login %}


{% block new_posts %}
<!-- client popular posts -->
<section class="client_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-10 mx-auto">
        <div class="heading_container">
          <h2>
            {{user.username}}'s Posts
          </h2>
        </div>
        {% for post in paginated_posts %}
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="detail-box">
                <h4>
                  {{post.user.username}}
                </h4>
                <a href="{% url 'main:individual_post' post.id %}" >
                  {{post.title}}
                </a>
                <p>
                  {{post.category}}
                </p>
                <img src="{% static 'main/images/quote.png' %}" alt="">
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>


{% if paginated_posts.has_previous %}
    <a href="?page=1">Primera</a>
    {% if paginated_posts.previous_page_number != 1 %}
    <a href="?page={{paginated_posts.previous_page_number}}">Previous</a>
    {% endif %}
{% endif %}

{% for num in paginated_posts.paginator.page_range %}
    {% if paginated_posts.number == num %}
        <a href="?page={{num}}">{{num}}</a>
    {% elif num > paginated_posts.number|add:'-3' and num < paginated_posts.num|add:'3' %}
        <a href="?page={{num}}">{{num}}</a>
    {% endif %}

{% endfor %}

{% if paginated_posts.has_next %}
    {% if paginated_posts.next_page_number != paginated_posts.paginator.num_pages %}
    <a href="?page={{paginated_posts.next_page_number}}">Next</a>
    {% endif %}
    <a href="?page={{paginated_post.paginator.num_pages}}">Last</a>
{% endif %}


<!-- end client section -->
{% endblock new_posts %}

main/templates/main/posts.html
{% extends "users/login.html" %}
{% load static %}


{% block login %}{% endblock %}

{% block new_posts %}
<!-- client popular posts -->
<section class="client_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-10 mx-auto">
        <div class="heading_container">
          <h2>
            Posts
          </h2>
        </div>
        {% for post in paginated_posts %}
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="detail-box">
                <h4>
                  {{post.user.username}}
                </h4>
                <a href="{% url 'main:individual_post' post.id %}" >
                  {{post.title}}
                </a>
                <p>
                  {{post.category}}
                </p>
                <img src="{% static 'main/images/quote.png' %}" alt="">
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>


{% if paginated_posts.has_previous %}
    <a href="?page=1">Primera</a>
    {% if paginated_posts.previous_page_number != 1 %}
    <a href="?page={{paginated_posts.previous_page_number}}">Previous</a>
    {% endif %}
{% endif %}

{% for num in paginated_posts.paginator.page_range %}
    {% if paginated_posts.number == num %}
        <a href="?page={{num}}">{{num}}</a>
    {% elif num > paginated_posts.number|add:'-3' and num < paginated_posts.num|add:'3' %}
        <a href="?page={{num}}">{{num}}</a>
    {% endif %}

{% endfor %}

{% if paginated_posts.has_next %}
    {% if paginated_posts.next_page_number != paginated_posts.paginator.num_pages %}
    <a href="?page={{paginated_posts.next_page_number}}">Next</a>
    {% endif %}
    <a href="?page={{paginated_post.paginator.num_pages}}">Last</a>
{% endif %}


<!-- end client section -->
{% endblock new_posts %}

main/templates/main/work.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Spering</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="index.html">
            <img src="images/logo.png" alt="" />
            <span>
              Spering
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html"> About</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="work.html">Work </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="category.html"> Category </a>
              </li>
            </ul>
            <div class="user_option">
              <a href="">
                <span>
                  Login
                </span>
              </a>
              <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
          <div>
            <div class="custom_menu-btn ">
              <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
              </button>
            </div>
          </div>

        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>


  <!-- freelance section -->

  <section class="freelance_section layout_padding">
    <div id="accordion">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-5 offset-md-1">
            <div class="detail-box">
              <div class="heading_container">
                <h2>
                  Work Freelaner Has Done
                </h2>
              </div>
              <div class="tab_container">
                <div class="t-link-box" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <div class="img-box">
                    <img src="images/f1.png" alt="">
                  </div>
                  <div class="detail-box">
                    <h5>
                      $250 Million
                    </h5>
                    <h3>
                      Paid to Freelancers
                    </h3>
                  </div>
                </div>
                <div class="t-link-box collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <div class="img-box">
                    <img src="images/f2.png" alt="">
                  </div>
                  <div class="detail-box">
                    <h5>
                      2 Million
                    </h5>
                    <h3>
                      Paid Invoices
                    </h3>
                  </div>
                </div>
                <div class="t-link-box collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  <div class="img-box">
                    <img src="images/f3.png" alt="">
                  </div>
                  <div class="detail-box">
                    <h5>
                      700,000
                    </h5>
                    <h3>
                      Worldwide Freelancer
                    </h3>
                  </div>
                </div>
                <div class="t-link-box collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                  <div class="img-box">
                    <img src="images/f4.png" alt="">
                  </div>
                  <div class="detail-box">
                    <h5>
                      98%
                    </h5>
                    <h3>
                      Customer <br>
                      Satisfaction Rate
                    </h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="collapse show" id="collapseOne" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="img-box">
                <img src="images/freelance-img.jpg" alt="">
              </div>
            </div>
            <div class="collapse" id="collapseTwo" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="img-box">
                <img src="images/freelance-img.jpg" alt="">
              </div>
            </div>
            <div class="collapse" id="collapseThree" aria-labelledby="headingThree" data-parent="#accordion">
              <div class="img-box">
                <img src="images/freelance-img.jpg" alt="">
              </div>
            </div>
            <div class="collapse" id="collapseFour" aria-labelledby="headingfour" data-parent="#accordion">
              <div class="img-box">
                <img src="images/freelance-img.jpg" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end freelance section -->

  <!-- info section -->

  <section class="info_section ">
    <div class="info_container layout_padding-top">
      <div class="container">
        <div class="info_top">
          <div class="info_logo">
            <img src="images/logo.png" alt="" />
            <span>
              Spering
            </span>
          </div>
          <div class="social_box">
            <a href="#">
              <img src="images/fb.png" alt="">
            </a>
            <a href="#">
              <img src="images/twitter.png" alt="">
            </a>
            <a href="#">
              <img src="images/linkedin.png" alt="">
            </a>
            <a href="#">
              <img src="images/instagram.png" alt="">
            </a>
            <a href="#">
              <img src="images/youtube.png" alt="">
            </a>
          </div>
        </div>

        <div class="info_main">
          <div class="row">
            <div class="col-md-3 col-lg-2">
              <div class="info_link-box">
                <h5>
                  Useful Link
                </h5>
                <ul>
                  <li class=" active">
                    <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="">
                    <a class="" href="about.html">About </a>
                  </li>
                  <li class="">
                    <a class="" href="work.html">Work </a>
                  </li>
                  <li class="">
                    <a class="" href="category.html">Category </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 ">
              <h5>
                Offices
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3 col-lg-2 offset-lg-1">
              <h5>
                Information
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3  offset-lg-1">
              <div class="info_form ">
                <h5>
                  Newsletter
                </h5>
                <form action="">
                  <input type="email" placeholder="Email">
                  <button>
                    Subscribe
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-9 col-md-10 mx-auto">
            <div class="info_contact layout_padding2">
              <div class="row">
                <div class="col-md-3">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="images/location.png" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Location
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-4">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="images/mail.png" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        demo@gmail.com
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-5">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="images/call.png" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Call +01 1234567890
                      </h6>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section ">
    <div class="container">
      <p>
        &copy; <span id="displayDate"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- end  footer section -->


  <script src="js/jquery-3.4.1.min.js"></script>
  <script src="js/bootstrap.js"></script>
  <script src="js/custom.js"></script>



</body>
</body>

</html>